/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.chasen.cabocha;

public final class ParsingAlgorithm {
  public final static ParsingAlgorithm SHIFT_REDUCE = new ParsingAlgorithm("SHIFT_REDUCE", CaboChaJNI.SHIFT_REDUCE_get());
  public final static ParsingAlgorithm TOURNAMENT = new ParsingAlgorithm("TOURNAMENT", CaboChaJNI.TOURNAMENT_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ParsingAlgorithm swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ParsingAlgorithm.class + " with value " + swigValue);
  }

  private ParsingAlgorithm(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ParsingAlgorithm(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ParsingAlgorithm(String swigName, ParsingAlgorithm swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ParsingAlgorithm[] swigValues = { SHIFT_REDUCE, TOURNAMENT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

